### ISSUE TITLE
/dev/mmcblk devices broken in format/flash scripts

### ISSUE THREAD

**Issue by varGeneric** [avafinger/nanopi-a64-firmware#10]
The scripts just append the partition number being used, which is fine for sda1/2/3 but mmcblk device follow the scheme of mmcblk(device#)p(partion), which breaks the script. Temporary workaround is just editing the script to add p# instead.

**Comment by varGeneric** [comment]
~~Looking further, it should have been fixed when merging #4. Script seems to have changed since.~~ 
#4 was never merged. It should fix this though...

**Comment by avafinger** [comment]
It should have been fixed on https://github.com/avafinger/nanopi-a64-firmware/blob/master/burn_sdcard_v2.sh#L37

Try that instead if that pull request does not work.

**Comment by varGeneric** [comment]
I tried it initially, and it did not work since my computer was automounting the partitions after they were formatted. Just tried after stopping the udisks2 service, and it ~~formats fine but errors after not finding "rootfs_nanopia64_rc3.tar.gz"~~ works fine, I just didn't follow instructions. Since the instructions say to use format_sd.sh and flash_sd.sh, I didn't realize burn_sdcard_v2 was usable. Should readme be updated?

**Comment by avafinger** [comment]
It's actually there:
https://github.com/avafinger/nanopi-a64-firmware#instructions-for-new-image

**Build v1** (for old Image)
**Build v2** (for new image with full working USB receptacles)

Maybe it's a bit messy and should be more clear, i have plans to Build v3 with mainline kernel if it works this time.

**Comment by varGeneric** [comment]
Yeah it is kinda cluttered, I eventually realized it was there, and was suggesting cleaning it up (why would you want the older builds anyway?).
